In [40]:
def convert_date_to_age(date):
    y_study = 2015
    m_study = 10
    d_study = 15
    date,_ = date.split(' ')
    y,m,d = date.split('-')
    age = (y_study-float(y)) + (m_study-float(m))/12.0 + (d_study-float(d))/365.0
    return age

In [41]:
import pandas as pd
import os
import pickle
import numpy as np

xl = pd.ExcelFile('/home/sohrob/Dropbox/Data/CS120Clinical/CS120Final_Baseline.xlsx')
df = xl.parse('Sheet1')

ind_subject = np.where(df.loc[0:999,'ID'].astype(str)!='nan')[0]
subjects = df.loc[ind_subject, 'ID'].astype(str)
gender = df.loc[ind_subject, 'demo09'].astype(int)
age = df.loc[ind_subject, 'demo08'].astype(str)
age = age.apply(convert_date_to_age)
employment = df.loc[ind_subject, 'slabels02'].astype(int)

demo = pd.concat([subjects, gender, age, employment], axis=1)
demo.columns = ['ID','gender','age','employment']
demo = demo.reset_index(drop=True)

with open('demo.dat','w') as f:
    pickle.dump(demo, f)
f.close()

In [42]:
demo

          ID  gender        age  employment
0      25349       1  40.658447           1
1      38880       2  54.633790           1
2      39468       2  44.789498           1
3      62977       2  58.381050           1
4      97397       1  31.644749           1
5      98384       2  53.225342           1
6     106743       2  43.631050           1
7     345921       2  40.128311           1
8     391378       1  47.199543           1
9     411896       2  42.161187           5
10    428255       2  47.128311           1
11    433874       2  34.194064           1
12    489868       1  52.941324           2
13    506107       1  37.894749           1
14    555220       2  58.038356           4
15    560623       2  40.736301           1
16    564447       2  41.303196           1
17    575209       2  35.336073           5
18    606449       2  35.066895           1
19    616751       2  35.728082           1
20    619634       2  51.788356           1
21    630742       2  43.855251           1
22    636646       2  57.102511           3
23    639010       2  27.277397           2
24    662410       2  52.952283           3
25    765488       1  38.172146           1
26    820387       2  43.958904           1
27    827285       1  38.277397           1
28    828778       2  44.058676           2
29    831987       1  61.706164           2
..       ...     ...        ...         ...
181  LR112KQ       2  21.780137           1
182  MQ077WG       2  32.392009           1
183  NJ280ID       2  47.967123           1
184  NQ003SV       1  41.521918           1
185  QE210HJ       2  37.532877           1
186  QG620BT       2  57.446804           3
187  SP157RF       2  33.908447           1
188  TP903SN       2  38.849772           1
189  UQ050PR       1  24.841553           1
190  WT253RB       2  52.013699           2
191  XF600QF       2  25.088813           1
192  XU620RL       2  39.163927           1
193  JB320SW       1  51.706164           1
194  1135515       2  26.550457           1
195  1114936     999  25.650228           1
196  1155329       2  37.102511           1
197   249499       2  30.844292           1
198   510909       2  56.077854           1
199   733021       2  53.333333           1
200   906629       1  25.266438           1
201  1022235       2  42.172146           5
202  1051651       2  28.922146           2
203  1084240       2  28.416667           1
204  1184498       2  55.797717           5
205  1229114       1  40.705023           3
206  1425272       2  62.139269           2
207  1497026       1  28.708904           3
208  1549226       2  38.316895           2
209  1550259       2  21.297717           1
210  QC647KS       2  24.366210           1

[211 rows x 4 columns]